#!/usr/bin/python3
def raise_exception():
    return int(9,'l')
